variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe'
  XUNIT_PATH: packages\xunit.runner.console.2.3.1\tools\net452
  UNITTEST_FOLDER: '.\tests\ImageHunt.Test\bin\Release\'

language: csharp
solution: ./ImageHuntSolution.sln

stages:
  - build
  - test

install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Console -Version 3.11.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ImageHuntSolution.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.0/tools/nunit3-console.exe ./ImageHunt.Test/bin/Release/ImageHunt.Test.dll

before_deploy:
- dotnet pack -c Release
skip_cleanup: true

deploy:
  provider: script
  script: dotnet nuget push ./ImageHuntSolution/bin/Release/ImageHuntSolution.*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: main