language: csharp
solution: ./ImageHuntSolution.sln
mono: 
- latest
install:
- dotnet restore ./ImageHuntSolution.sln
script:
- dotnet build ./ImageHuntSolution.sln
- dotnet test ImageHunt.Test/ImageHunt.Test.csproj
before_deploy:
- dotnet pack -c Release
skip_cleanup: true
deploy:
  provider: script
  script: dotnet nuget push ./ImageHuntSolution/bin/Release/ImageHuntSolution.*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: main