language: csharp
solution: ImageHuntSolution.sln
mono: none
dotnet: 2.2

install:
- dotnet restore ImageHuntSolution.sln
script:
- dotnet build ImageHuntSolution.sln
- dotnet test ImageHunt.Tests/ImageHunt.Tests.csproj
before_deploy:
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./src/Npam/bin/Release/Npam.*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: main