os: linux
language: csharp
solution: ./ImageHuntSolution.sln

mono: none
dotnet: 2.2

install:
- dotnet restore ./ImageHunt/ImageHunt/ImageHunt.csproj
- dotnet restore ./ImageHuntSolution.sln

script:
- dotnet build ./ImageHunt/ImageHunt/ImageHunt.csproj
- dotnet test ./ImageHunt.Test/ImageHunt.Test.csproj

skip_cleanup: true