language: csharp
solution: ImageHuntSolution.sln
mono: none
dotnet: 2.2.0
install:
  - nuget restore ImageHuntSolution.sln
  - nuget install NUnit.Console -Version 3.11.0 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release ImageHuntSolution.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.0/tools/nunit3-console.exe ./ImageHunt.Tests/bin/Release/ImageHunt.Tests.dll