os: linux
language: csharp
solution: ./ImageHuntSolution.sln

mono: none
dotnet: 2.2

install:
- dotnet restore ./ImageHunt/ImageHunt/ImageHunt.csproj
- dotnet restore ./ImageHunt/ImageHunt.UWP/ImageHunt.UWP.csproj

script:
- dotnet clean ./ImageHunt/ImageHunt/ImageHunt.csproj
- dotnet clean ./ImageHunt/ImageHunt.UWP/ImageHunt.UWP.csproj

- dotnet build ./ImageHunt/ImageHunt/ImageHunt.csproj
- dotnet build ./ImageHunt/ImageHunt.UWP/ImageHunt.UWP.csproj

- dotnet test ./ImageHunt.Test/ImageHunt.Test.csproj

skip_cleanup: true

deploy:
  provider: script
  script: dotnet nuget push ./ImageHuntSolution/bin/Release/ImageHuntSolution.*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: main